### ISSUE TITLE
Markdown converter

### ISSUE THREAD

**Issue by WilsontheWolf** [chroventer/glitchfaq#2]
You said you wanted a markdown converter. I googled and found this. Might make a project for it. https://ourcodeworld.com/articles/read/396/how-to-convert-markdown-to-html-in-javascript-using-remarkable

**Comment by WilsontheWolf** [comment]
made one. Fetches the raw github data every five minutes https://glitch-faq.glitch.me/

**Comment by chroventer** [comment]
> You said you wanted a markdown converter. I googled and found this. Might make a project for it.

@WilsontheWolf, I will read the documentation and try to integrate it.
Thanks for the hard work!

**Comment by chroventer** [comment]
> made one. Fetches the raw github data every five minutes [glitch-faq.glitch.me](https://glitch-faq.glitch.me/)

I would rather prefer axios or node-fetch over unirest.

**Comment by chroventer** [comment]
> made one. Fetches the raw github data every five minutes [glitch-faq.glitch.me](https://glitch-faq.glitch.me/)

Also, there are a few things I am confused about 'why did you use while loop'.

**Comment by WilsontheWolf** [comment]
>Also, there are a few things I am confused about 'why did you use while loop'.



it fetches the raw GitHub data every five minutes. This allows it if someone is on the site and we update it then they can get the new data, even if it doenst restart.
